### ISSUE TITLE
WP CLI WITH IMPORT

### ISSUE THREAD

**Issue by jeanrinvil** [soflyy/wp-all-import-action-reference#66]
Well, when running WP CLI, the following filters do not launch : 

add_filter( 'wp_all_import_multi_glue', 'wpai_wp_all_import_multi_glue', 10, 1 );
add_filter( 'wp_all_import_product_attributes_delimiter', 'wpai_wp_all_import_product_attributes_delimiter', 10, 3 );
add_action( 'pmxi_saved_post', 'my_saved_post', 10, 3 );

Theses fonctions are in my functions.php 
by `require_once 'inc/import.php';`

When I run this with processing cron, it works.

**Comment by trey8611** [comment]
Hi @rinvil,

I've tested and can confirm that these hooks run via WP-CLI imports, so there must be something else going wrong here. You'll need to reach out to support at: https://www.wpallimport.com/support/. Keep in mind that we can't help with custom code, but we can confirm that the hooks are running for you.

I'm locking this since we do not provide support via GitHub.
